name: build

on:
  workflow_dispatch:

permissions:
  id-token: write # for azure/login with OpenID Connect
  contents: read

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main

      - name: Replace tokens in src/MyHealth.Web/appsettings.json with env
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["src/MyHealth.Web/appsettings.json"]'
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}

      # dotnet build
      # https://docs.microsoft.com/ja-jp/dotnet/architecture/devops-for-aspnet-developers/actions-build
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.0.0
      - name: Restore .NET dependencies
        run: dotnet restore ./MHC_ASPNetCore.sln
      - name: Build .NET app
        run: dotnet publish ./MHC_ASPNetCore.sln -c Release -o ./obj/Docker/publish

      # docker build & push
      # https://docs.microsoft.com/ja-jp/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: Build docker image, login to ACR and push image to ACR
        run: |
          # Build docker image
          docker build . -t ${{ secrets.ACR }}/myhealth.web:$TAG -t ${{ secrets.ACR }}/myhealth.web:latest
          # Login to ACR
          # https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md#authenticating-to-a-registry-with-azure-cli
          az acr login -n ${{ secrets.ACR }}
          # Push image to ACR
          docker push -a ${{ secrets.ACR }}/myhealth.web
        env:
          TAG: ${{ github.run_number }}
        working-directory: ./src/MyHealth.Web

      # Using data from the triggering workflow
      # https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
      - name: Save Run-Number as artifact
        env:
          TAG: ${{ github.run_number }}
        run: |
          mkdir -p ./tags
          echo $TAG > ./tags/tag
      - uses: actions/upload-artifact@v3
        with:
          name: tag
          path: tags/
